### ISSUE TITLE
Commands error

### ISSUE THREAD

**Issue by Axxiar** [Hypermario/TUMO#2]
**Description :**
The bot isn't reacting to the commands as expected. I'm just trying basics commands like `;suggest` or `;question`

**Screenshots**
![image](https://user-images.githubusercontent.com/70155662/109361322-097d6e80-7889-11eb-8c41-a151e1156bf6.png)

I tried to delete and clone again but it's the same.

**Comment by Hypermario** [comment]
il faut que tu fasse kick et re join le bot de ton serveur en ayant le client d'allumé.
dans info.json ton serveur n'a pas été enregistré ou tu l'as supprimé

**Comment by Axxiar** [comment]
ok

**Comment by AXXIAR** [comment]
Ca marche merci

**Comment by Axxiar** [comment]
Ca a marché merci
