### ISSUE TITLE
Question sur le code (branche AXXIAR-dev) 

### ISSUE THREAD

**Issue by Axxiar** [Hypermario/TUMO#4]
![Screenshot_20210228_163053.jpg](https://user-images.githubusercontent.com/70155662/109424147-bd464180-79e2-11eb-9d6b-9a5a857650be.jpg)

Sur le code ci dessus pour la commande qui "étire" du texte je voulais tester si texte est vide pour renvoyer une demande à l'utilisateur de donner son texte. Mais visiblement ça marche pas à cause du paramètre *  prit en compte au début (`...,*,texte`) 

j'ai essayer de faire `..., *texte` _avec l'étoile et 'texte' collé_ et ça marche mais par contre c'est le `.join(" ")` qui marche plus parce qu'il renvoie juste le texte, sans espaces

**Comment by Hypermario** [comment]
avec un if (texte != "") ca fonctionne pas ??

sinon la seule maniere qu'un utilisateur envoie un message vide c'est en envoyant une image sans commentaire...

**Comment by Axxiar** [comment]
J'ai pas l'impression
